// SHOT LIST. Resolves every shot's narration anchor against story/timeline.gen.json, proves the
// shots tile the film with no gap or overlap, checks each duration against the editing rhythm,
// and writes docs/shotlist.md plus story/shots.gen.json (the cue table the film will read).
//
//   node pipeline/shotlist.mjs        (run pipeline/timing.mjs first after replacing any clip)
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const T = JSON.parse(readFileSync(join(ROOT, "story/timeline.gen.json"), "utf8"));
const { SHOTS, LOCATIONS } = await import(pathToFileURL(join(ROOT, "story/shots.mjs")).href);
const FPS = T.fps, byClip = new Map(T.clips.map((c) => [c.clip, c]));
const die = (m) => { console.error(`shotlist: ${m}`); process.exit(1); };

const resolveAnchor = (a, id) => {
  if (a.frame !== undefined) return a.frame;
  const c = byClip.get(a.clip) ?? die(`${id}: no clip ${a.clip}`);
  if (a.at === "start") return c.start.frame + (a.off ?? 0);
  if (a.at === "end") return c.end.frame + (a.off ?? 0);
  const hits = c.words.filter((x) => x.w === a.word);
  const hit = hits[a.nth - 1] ?? die(`${id}: clip ${a.clip} has ${hits.length} × "${a.word}", asked for #${a.nth}`);
  return (a.edge === "end" ? hit.f1 : hit.f0) + (a.off ?? 0);
};

const shots = SHOTS.map((s) => ({ ...s, start: resolveAnchor(s.from, s.id) }));
shots.forEach((s, i) => { s.end = i + 1 < shots.length ? shots[i + 1].start : T.totalFrames; s.frames = s.end - s.start; });
if (shots[0].start !== 0) die(`the first shot starts at ${shots[0].start}, not 0`);
for (const s of shots) if (s.frames <= 0) die(`${s.id} has ${s.frames} frames: anchors out of order`);

// the narration each shot carries: every word whose middle falls inside it
for (const s of shots) {
  const parts = [];
  for (const c of T.clips) {
    const ws = c.words.filter((x) => (x.f0 + x.f1) / 2 >= s.start && (x.f0 + x.f1) / 2 < s.end);
    if (ws.length) parts.push({ clip: c.clip, text: ws.map((x) => x.raw).join(" ") });
  }
  s.narration = parts;
  s.clip = Number(s.id.slice(0, 2));
}

// editing-rhythm checks (brief: shots 2-5 s, montage 1-2.5 s, emotional holds may run longer)
const sec = (f) => f / FPS;
const warnings = [];
for (const s of shots) {
  const d = sec(s.frames);
  if (s.kind === "montage" && (d < 1 || d > 2.5)) warnings.push(`${s.id} montage shot is ${d.toFixed(2)} s (target 1–2.5 s)`);
  if (!s.kind && (d < 1.5 || d > 5.5)) warnings.push(`${s.id} is ${d.toFixed(2)} s (target 2–5 s)`);
  if (s.kind === "insert" && (d < 1 || d > 2.5)) warnings.push(`${s.id} insert is ${d.toFixed(2)} s (target 1–2.5 s)`);
  if (s.kind === "hold" && d < 1.3) warnings.push(`${s.id} is a hold but only ${d.toFixed(2)} s`);
}

writeFileSync(join(ROOT, "story/shots.gen.json"), JSON.stringify({ _generated: "by pipeline/shotlist.mjs; do not edit", fps: FPS, totalFrames: T.totalFrames, shots: shots.map(({ from, ...s }) => s) }, null, 1) + "\n");

// ---------- docs/shotlist.md ----------
const ts = (f) => { const s = f / FPS, m = Math.floor(s / 60); return `${String(m).padStart(2, "0")}:${(s - m * 60).toFixed(2).padStart(5, "0")}`; };
const AGES = { A: "A · Simon the fisherman", B: "B · the disciple", C: "C · Passion / Resurrection", D: "D · missionary", E: "E · Rome, aged", "—": "— (not in shot)" };
const L = [];
L.push("# Shot list — The Apostle Peter", "");
L.push(`Generated by \`node pipeline/shotlist.mjs\` from \`story/shots.mjs\` and the measured narration timing. **${shots.length} shots, ${T.totalFrames} frames, ${ts(T.totalFrames)} at ${FPS} fps, ${T.width}×${T.height}.** Frame ranges are inclusive and absolute. Every shot starts on a word of the narration, so replacing a clip and re-running the pipeline moves every cut with the voice.`, "");
L.push("◆ marks a creative decision that is the director's own rather than the brief's. Each can be vetoed in one line.", "");
L.push("**Peter's ages:** " + Object.entries(AGES).filter(([k]) => k !== "—").map(([, v]) => v).join(" · "), "");
L.push("**Arc of light and colour:** gold (01–05) → divine white-gold (06) → cold blue darkness (07) → dawn (08) → fire (09) → stone (10–11) → gold (12–13).", "");
L.push("## At a glance", "", "| Shot | Frames | Dur | Location | Peter | What happens |", "|---|---|---:|---|---|---|");
for (const s of shots) L.push(`| ${s.id} | ${s.start}–${s.end - 1} | ${sec(s.frames).toFixed(1)} s | ${s.loc} | ${s.age} | **${s.title}**${s.kind ? ` · _${s.kind}_` : ""} |`);
L.push("", "## Locations", "");
for (const [k, v] of Object.entries(LOCATIONS)) L.push(`- **${k}** — ${v}`);
L.push("", "## Checks", "", `- Shots tile frames 0–${T.totalFrames - 1} with no gap and no overlap: **pass**.`);
L.push(warnings.length ? `- Rhythm notes (${warnings.length}): ${warnings.join("; ")}.` : "- Every shot is inside its rhythm target: **pass**.", "");
for (const c of T.clips) {
  const cs = shots.filter((s) => s.clip === c.clip);
  L.push(`## Clip ${String(c.clip).padStart(2, "0")} — ${c.title}`, "");
  L.push(`Audio \`${c.file}\`: ${c.duration.toFixed(3)} s, frames ${c.start.frame}–${c.end.frame - 1} (${ts(c.start.frame)}–${ts(c.end.frame)}), then ${c.gapAfterFrames || T.tailFrames} frames of ${c.gapAfterFrames ? "breathing room" : "tail"}.`, "");
  for (const s of cs) {
    const narr = s.narration.length ? s.narration.map((p) => (p.clip !== c.clip ? `(clip ${String(p.clip).padStart(2, "0")}) ` : "") + `_${p.text}_`).join(" ") : "— (no narration: breathing room)";
    L.push(`### ${s.id} — ${s.title}`, "");
    L.push(`**Frames ${s.start}–${s.end - 1}** · ${s.frames} frames · **${sec(s.frames).toFixed(2)} s** · ${ts(s.start)}–${ts(s.end)}${s.kind ? ` · ${s.kind}` : ""}`, "");
    L.push("| | |", "|---|---|");
    L.push(`| Narration | ${narr} |`);
    L.push(`| Location | **${s.loc}** · ${LOCATIONS[s.loc].split(":")[0]} |`);
    L.push(`| Peter | ${AGES[s.age] ?? s.age} — ${s.emotion} |`);
    L.push(`| Action | ${s.action} |`);
    L.push(`| Camera | ${s.cam} · **move:** ${s.move} |`);
    L.push(`| Foreground | ${s.fg} |`);
    L.push(`| Background | ${s.bg} |`);
    L.push(`| Lighting | ${s.light} |`);
    L.push(`| Transition out | ${s.trans} |`);
    L.push(`| Ambient sound | ${s.sound} |`);
    L.push(`| Music | ${s.music} |`, "");
  }
}
writeFileSync(join(ROOT, "docs/shotlist.md"), L.join("\n"));
console.log(`shotlist: ${shots.length} shots over ${T.totalFrames} frames`);
for (const x of warnings) console.log(`  note: ${x}`);
